// <auto-generated />
namespace Atum.Database.Surveillance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DbMigration14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbMigration14));
        
        string IMigrationMetadata.Id
        {
            get { return "201501210153495_DbMigration14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
